# sudo docker-compose up -d
services:
  php:
    #image: php:8.5-fpm
    build: './infrastracture/etc/php'
    container_name: crm-php
    #restart: always
    user: "www-data:www-data"
    volumes:
    - ./infrastracture/.bashrc:/root/.bashrc
    - ./infrastracture/.bashrc:/home/www-data/.bashrc
    - .:/var/www/crm/
    - ./bootstrap/cache/:/var/www/crm/bootstrap/cache/
    #- ./infrastracture/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    working_dir: /var/www/crm/
    links:
    - cache
    ports:
      - "9003:9003"
  web:
    #image: nginx:stable
    build: './infrastructure/etc/nginx'
    container_name: crm-web
    #restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - ./infrastracture/.bashrc:/home/www-data/.bashrc
    - .:/var/www/crm/:z
    - ./infrastracture/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./infrastracture/etc/nginx/static.conf:/etc/nginx/conf.d/static.conf
    - ./infrastracture/etc/nginx/ssl/:/etc/ssl/
    - ./infrastracture/etc/nginx/conf.d:/etc/nginx/conf.d/
    links:
    - cache
    - php
    depends_on:
    - php
    user: "root:www-data"
  cache:
    image: redis
    container_name: crm-cache
    #restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./infrastracture/etc/redis/redis.conf:/etc/redis/redis.conf
